clear; clc; %close all;

load('opt_data.mat');
iter_num = 2000;
%% Alg_3_Norm_sign

eta = 0.64;
alpha = 85;
beta = 5;
s0 = 1;
gamma = 0.99;

[xminuxbar_Alg_3_Norm_sign, ...
 sq_grad_Alg_3_Norm_sign,...
 transmit_Alg_3_Norm_sign] = Alg_3_Norm_signE(L_aug, ...
                                     y_temp, ...
                                     d, ...
                                     nodes_num, ...
                                     gc, ...
                                     function_lambda, ...
                                     function_aalpha, ...
                                     features, ...
                                     labels, ...
                                     batch_size, ...
                                     iter_num, ...
                                     eta, ...
                                     alpha, ...
                                     beta, ...
                                     s0, ...
                                     gamma);

n = nodes_num;
ef = n^2;

T = iter_num;
p_Alg_3_Norm_sign = sq_grad_Alg_3_Norm_sign/ef + xminuxbar_Alg_3_Norm_sign/n;

for i=3:T
    p_Alg_3_Norm_sign(i)=min(p_Alg_3_Norm_sign(i-1:i));
end


figure;
semilogy(p_Alg_3_Norm_sign, '-', 'LineWidth', 2);

