clear; clc; %close all;

load('opt_data.mat');
iter_num = 2000;


%% Alg_1_Norm_sign

eta = 1.28;
alpha = 85;
beta = 5;
psi = 0.05;
iter_numC3=5000;
[xminuxbar_Alg_1_Norm_sign, ...
 sq_grad_Alg_1_Norm_sign,...
 transmit_Alg_1_Norm_sign] = Alg_1_Norm_signE(L_aug, ...
                                     y_temp, ...
                                     d, ...
                                     nodes_num, ...
                                     gc, ...
                                     function_lambda, ...
                                     function_aalpha, ...
                                     features, ...
                                     labels, ...
                                     batch_size, ...
                                     iter_numC3, ...
                                     eta, ...
                                     alpha, ...
                                     beta, ...
                                     psi);

n = nodes_num;
ef = n^2;

T = iter_numC3;
p_Alg_1_Norm_sign = sq_grad_Alg_1_Norm_sign/ef + xminuxbar_Alg_1_Norm_sign/n;

for i=3:T
    p_Alg_1_Norm_sign(i)=min(p_Alg_1_Norm_sign(i-1:i));
end


figure;
semilogy(p_Alg_1_Norm_sign, '-', 'LineWidth', 2);

set(gca,'FontSize', 10);
xticks(0:500:iter_numC3);
xlabel('Number of communication rounds','Interpreter', 'latex', ...
        'FontSize', 15, 'FontWeight','bold');
ylabel('$P(T)$', 'Interpreter','latex', ...
        'FontSize', 15, 'FontWeight','bold');
legend({'Alg-1 Norm-sign';}, ...
       'Interpreter', 'latex', 'FontSize', 10, 'FontWeight','bold');